config/routes.rb
Rails.application.routes.draw do

    devise_for :users

    #messages
    resources :conversations do
      resources :messages
    end

    #users
    get 'users/:id' => 'users#show'
    resources :users, only: [:show] do
      resources :reviews
    end

    #posts & resource tags
    resources :posts

    resources :transactions


    #tags
    resources :tags, only: [:create]

    #post tags
    resources :post_tags, only: [:create, :destroy]

    #categories
    resources :categories, only: [:index, :show] do
      resources :posts, only: [:index, :show]
    end

    #Sessions routes
    resources :sessions, only: [:create, :new]
    delete 'sessions', to: 'sessions#logout'

    # resources :search, only: [:index]
    get '/search', :to => 'search#index'

  root to: 'categories#index'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to 	:loaner, class_name: "User"
	belongs_to 	:category

	has_many  	:post_tags
	has_many	  :tags, through: :post_tags
  has_many 	  :transactions

	validates 	:title, :description, :price, :status, :loaner_id, :category_id, :city, :zip_code, presence: true
  
  #the validation below is neccessary because false values do not pass validation tests
  validates_inclusion_of :negotiable, in: [true, false]

  #location-api
  scope :search, -> (search_term) { left_outer_joins(:tags).where('lower(name) LIKE ? OR lower(title) LIKE ?', "%#{search_term.downcase}%", "%#{search_term.downcase}%").distinct.order('id DESC') }
  scope :in_zips, -> (zip_codes) { where(zip_code: zip_codes) }

  #paperclip
  has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb:"150x150#"}, default_url: "no_image_available.png"
  validates_attachment_content_type :image, content_type: ["image/jpeg", "image/gif", "image/png"]

  #search bar
  # def self.search(search_term)
  #   by_tag = self.joins(:tags).where('lower(name) LIKE ?', "%#{search_term.downcase}%" ).distinct
  #   by_title = self.where('lower(title) LIKE ?', "%#{search_term.downcase}%").order('id DESC')
  #   return (by_tag | by_title).uniq
  # end

  # def self.search(search_term)
  #   # by_tag = self.joins(:tags).where('lower(name) LIKE %?% OR lower(title) LIKE %?%', search_term.downcase, search_term.downcase).distinct.order('id DESC')

  #   # by_title = self.where('lower(title) LIKE ?', "%#{search_term.downcase}%").order('id DESC')
  #   # return @search_results << (by_tag | by_title).uniq
  # end

  # def self.find_all_by_zips(zips)
  #   zips.each do |zip|
  #     matched_zips = @search_results.find_by(location: zip)
  #   end
  #   matched_zips
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

	def index
		search_term = params[:term]

		@posts = Post.all

		if params[:zip_code].length > 0
			params[:distance] = 10 if params[:distance].blank?
	    	zip_codes = ZipCodeAdapter.zip_search(params[:zip_code], params[:distance])
			@posts = @posts.in_zips(zip_codes)
		end

		@posts = @posts.search(search_term) if search_term

		@errors = ["No results found, ensure that your zipcode is real"] if @posts.empty?  
	end

	def new
		@post = Post.new
		@categories = Category.all
	end

	def create
		@categories = Category.all
		@post = current_user.posts.new(post_params)


		if @post.save
			redirect_to post_path(@post), notice: "Post was successfully created"
		else
			@errors = @post.errors.full_messages
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
		@tag = Tag.new
		@transaction = Transaction.new
	end

	def edit
		@post = Post.find(params[:id])
		@categories = Category.all
	end

	def update
		@categories = Category.all
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)

		if @post.save
			redirect_to post_path(@post), notice: "Post was successfully updated"
		else
			@errors = @post.errors.full_messages
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to categories_path, notice: "Post was successfully destroyed"
	end

	private

	def post_params
		params.require(:post).permit(:zip_code, :city, :title, :description, :price, :negotiable, :category_id, :status, :image)
	end

	def search_params
		params.require(:search).permit(:keyword)
 	end
end

app/views/posts/_form.html.erb
<%= form_for @post, url: {action: "create"}, html: {class: "post_form"}, local: true do |f| %>

	<div>
		<%= f.label "Title" %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label "Description" %>
		<%= f.text_area :description, size: "60x12" %>
	</div>
	<div>
		<%= f.label "Status of this post" %>
		<%= f.select :status, %w[open closed] %>
	</div>
	<div>
		<%= f.label "Price" %>
 		<%= f.text_field :price %>
	</div>
	<div>
		<%= f.label "Is the price negotiable?"%>
		<%= f.select :negotiable?, [["yes", true], ["no", false]] %>
	</div>
	<div>
		<%= f.label "Zip Code" %>
		<%= f.text_field :location %>
	</div>
	<div>
		<%= f.label "Select a Category"%>
		<%= f.select :category_id, options_from_collection_for_select(@categories, 'id', 'name')%>
	</div>
  	<%= f.submit "Create" %>
<% end %>

app/views/posts/edit.html.erb
<div class="post-directions">
	<p class="center">Please follow the guidelines below for creating a post</p>
	<ul class="post-directions-list">
		<li>Title should mention the items you are listing</li>
		<li>Use the description to explain what type of agreement you are looking for and the condition of the items you are listing</li>
		<li>Do not mark your post as closed until someone has booked your items or you are no longer offering your items up for rent</li>
		<li>Your price should be more than just a number. Please format it with a dollar amount and a time period. For example:</li>
		<ul>
			<li>$100 a month</li>
			<li>$10 a day for the entire toolbox</li>
			<li>$5 a day per sleeping bag</li>
		</ul>
		<li>Only share your contact info in the description if you feel comfortable</li>
	</ul>
</div>

<%= form_for @post, url: {action: "update"}, html: {class: "post-form", multipart: true} do |f| %>

	<div>
		<%= f.text_field :title, class: "title-input", placeholder: "Title"%>
	</div>
	<div>
		<%= f.text_area :description, class: "desc-input", placeholder: "Description"%>
	</div>
	<div>
		<%= f.label "Select a Category"%>
		<%= f.select :category_id, options_from_collection_for_select(@categories, 'id', 'name')%>
	</div>
	<div>
		<%= f.label "Price" %>
 		<%= f.text_field :price,  class: "price-input" %>
	</div>
	<div>
		<%= f.label "Zip Code" %>
		<%= f.text_field :zip_code %>
	</div>
	<div>
		<%= f.label "City" %>
		<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label "Status of this post" %>
		<%= f.select :status, %w[open closed] %>
	</div>
	<div>
		<%= f.label "Is the price negotiable?"%>
		<%= f.select :negotiable, [["yes", true], ["no", false]] %>
	</div>
	<div>
		<%= f.label "Image" %>
		<%= f.file_field :image %>
	</div>
  	<%= f.submit "Create" %>
<% end %>

<%= link_to 'Back', post_path(@post) %>

app/views/posts/index.html.erb
<h1>Search Results</h1>

<% @posts.each do |post| %>
  <ul class="posts-list">
  	<li><%= image_tag post.image.url(:thumb) %></li>
    <li><%= link_to post.title, post_path(post) %>, <%=post.price %> </li>
    <li><%= post.city %> </li>
    <p><%= post.description%></p>

    <% post.tags.each do |tag| %>
      <span class="single-tag-box"><%= tag.name %></span>
    <% end %>
  </ul>
<% end %>

app/views/posts/new.html.erb
<div class="post-directions">
	<h1 id="new-post-header">Create New Post</h1>
	<p class="guide-text">Please follow the guidelines below for creating a post</p>
	<ul class="post-directions-list">
		<li class="directions-list">Title should mention the items you are listing</li>
		<li class="directions-list">Use the description to explain what type of agreement you are looking for and the condition of the items you are listing</li>
		<li class="directions-list">Do not mark your post as closed until someone has booked your items or you are no longer offering your items up for rent</li>
		<li class="directions-list">Your price should be more than just a number. Please format it with a dollar amount and a time period. For example:</li>
		<ul>
			<li class="directions-list">$100 a month</li>
			<li class="directions-list">$10 a day for the entire toolbox</li>
			<li class="directions-list">$5 a day per sleeping bag</li>
		</ul>
		<li class="directions-list">Only share your contact info in the description if you feel comfortable</li>
	</ul>
</div>



<div class='container'>
	<%= form_for @post, url: {action: "create"}, html: {class: "post-form form-group", multipart: true}, class: 'form-control' do |f| %>

	<%= f.text_field :title, class: "title-input title-box title-text form-control", placeholder: "Title"%>

	<%= f.text_area :description, class: "desc-input new-post-text form-control", placeholder: "Description"%>

	<div class="form-horizontal">
		<div class="form-group form-attr-pad">
				<%= f.label :category, "Select A Category:", class: "control-label col-md-3 form-text" %>
				<div class="col-sm-10 form-attrs">
						<%= f.select :category_id, options_from_collection_for_select(@categories, 'id', 'name'), {}, { class: "control-label category-dropdown" } %>
				</div>
		</div>
		<hr class="half-rule"/>
		<div class="form-group form-attr-pad">
			<%= f.label :price, "Price:", class: "col-md-3 form-text" %>
				<div class="col-sm-3 form-attrs">
	 				<%= f.text_field :price,  class: "form-control", placeholder: "Ex: $5 a day" %>
				</div>
		</div>
		<hr class="half-rule"/>
		<div class="form-group form-attr-pad">
			<%= f.label :zip_code, "Zip Code:", class: "col-md-3 form-text" %>
				<div class="col-sm-10 form-attrs">
					<%= f.text_field :zip_code, class: "form-control" %>
				</div>
		</div>
		<hr class="half-rule"/>
		<div class="form-group form-attr-pad">
			<%= f.label :city, "City:", class: "col-md-3 form-text" %>
				<div class="col-sm-10 form-attrs">
					<%= f.text_field :city, class: "form-control" %>
				</div>
		</div>
		<hr class="half-rule"/>
		<div class="form-group form-attr-pad">
			<%= f.label :price_negotiate, "Is the Price Negotiable?", class: "col-md-3 form-text" %>
				<div class="col-sm-10 form-attrs">
					<%= f.select :negotiable, [["yes", true], ["no", false]], {}, { class: "form-control" } %>
				</div>
		</div>
		<hr class="half-rule"/>
		<div class="form-group form-attr-pad">
			<%= f.label :image, "Image:", class: "col-md-3 form-text" %>
				<div class="col-sm-10">
					<span class="btn btn-md btn-primary btn-file">
					Upload
					<%= f.file_field :image, id: "img-upload" %>
					</span>
					<span id="upload-filename"></span>
				</div>
		</div>

	  <%= f.submit "Create", class: "create-button" %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div>
	<p class="post-title"><%= @post.title %></p>

	<%= image_tag @post.image.url(:medium) %>

	<p class="post-description"><%= @post.description %></p>

	<table style="width:100%">
	  <tr>
	    <th class="table-headers">Price</th>
	    <th class="table-headers">Status</th> 
	    <th class="table-headers">Author</th>
	    <th class="table-headers">City</th>
	    <th class="table-headers">Zip Code</th>
	    <th class="table-headers">Negotiable?</th>
	  </tr>
	  <tr>
	    <td><%= @post.price %></td>
	    <td><%= @post.status %></td> 
		<td><%= link_to @post.loaner.user_name.capitalize, user_path(@post.loaner) %></td>
		<td><%= @post.city %></td>
		<td><%= @post.zip_code %></td>
	  <% if @post.negotiable %>
	  	<td>yes</td>
	  <% else %>
	  	<td>no</td>
	  <% end %>
	    </tr>
  	</table>



	<% if @post.loaner == current_user %>
		<div class="tag-box">
			<% @post.tags.each do |tag| %>
				<span class="single-tag-box"><%= link_to "x ", post_tag_path(tag, post_id: @post.id), method: "DELETE" %><%= tag.name %></span>
			<% end %>
		</div>
	<% else%>
		<div class="tag-box">
			<% @post.tags.each do |tag| %>
				<span class="single-tag-box"><%= tag.name %></span>
			<% end %>
		</div>
	<% end %>

</div>

<% if @post.loaner == current_user %>
	<div class="add-tags-box">
		<p>Add Tags To Your Post</p>

		<%= form_for @tag, as: :tag, url: tags_path, html: {id: "tag_form" } do |f| %>
			<div>
				<%= f.label "Tag Name" %>
				<%= f.text_field :name %>
				<%= f.hidden_field :post_id, value: @post.id %>
		  		<%= f.submit "Create" %>
			</div>
		<% end %>
	</div>
	<div>
		<p><span class="edit-btn"><%= link_to "Edit Post", edit_post_path(@post)%></span>
		<span class="delete-btn"><%= link_to "Delete Post", post_path(@post), method: "DELETE"%></span></p>
	</div>
<% end %>

<%= form_for @transaction, as: :transaction,  url: transactions_path do |f| %>
  <div>
    <%= f.label "Make an Offer" %>
    <%= f.hidden_field :borrower_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: @post.id %>

    <%= f.text_field :duration, placeholder: "How long?" %>
    <%= f.text_field :final_price, placeholder: "Final price" %>
  </div>
    <%= f.submit "Borrow" %>
<% end %>

<% @post.transactions.each do |transaction| %>
	<p>Duration:<%= transaction.duration  %></p>
	<p>Final Price:<%= transaction.final_price %></p>
<% end %>