config/routes.rb
Rails.application.routes.draw do

    devise_for :users

    #messages
    resources :conversations do
      resources :messages
    end

    #users
    get 'users/:id' => 'users#show'
    resources :users, only: [:show] do
      resources :reviews
    end

    #posts & resource tags
    resources :posts

    resources :transactions


    #tags
    resources :tags, only: [:create]

    #post tags
    resources :post_tags, only: [:create, :destroy]

    #categories
    resources :categories, only: [:index, :show] do
      resources :posts, only: [:index, :show]
    end

    #Sessions routes
    resources :sessions, only: [:create, :new]
    delete 'sessions', to: 'sessions#logout'

    # resources :search, only: [:index]
    get '/search', :to => 'search#index'

  root to: 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
	has_many	:posts

	validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
    
  end
end

app/views/categories/index.html.erb
<h1 class="profile-heading">Welcome</h1>
<hr class="half-rule"/>
<h4 class="header-text">What is Forever A Loaner?</h4>

<div class="index-body">
<p>Forever A Loaner is a service for people who want to borrow things from other people. That's it!</p>

<h4 class="header-text">How it works:</h4>
<p>You can browse by category or you can search in your area for something you need. Once you find what you need, go to the user's profile page and message them! You can send a message and negotiate what you would like from your transaction. Once you and the other user make an agreement, you can make an offer!</p>

<h4 class="header-text">Have something you want to loan out?</h4>
<p>You can create a post and advertise what you are willing to lend out. There are guidelines that you can follow when creating your post so you can reach the most people! Make sure to include a picture! After you post, people will start to message you about borrowing your things. You can negotiate with the user on duration and price. Once you come to an agreement, the user will make an offer.</p>

<h4 class="header-text">Want to make a review?</h4>
<p>After you and another user have made a transaction, you can review each other. You can review a user as a borrower or a lender. Reviews are very helpful to other users, so make sure you write reviews! After your transaction, go to the user's profile and you can leave a review depending on your relationship. If you borrowed something from them, write a review as a borrower. If you lent them something, write a review as a loaner. However, a transaction must occur before you can write a review.</p>
</div>

app/views/categories/show.html.erb
<h1 class="profile-heading"><%= @category.name%></h1>

<%= form_tag(posts_path, method: :get) do %>
  <%= text_field_tag :term, params[:term], placeholder: "Keyword" %>
  <%= text_field_tag :zip_code, params[:zip_code], placeholder: "Zip Code"%>
  <%= text_field_tag :distance, params[:distance], placeholder: "Distance In Miles" %>
  <%= submit_tag 'Search', name: nil %>
<% end %>

<% @posts.each do |post| %>
	<ul class="posts-list">
		<li><%= image_tag post.image.url(:thumb) %></li>
		<li><%= link_to post.title, post_path(post) %>, <%=post.price %> </li>
		<li><%= post.city %> </li>
		<p><%= post.description%></p>
		<% post.tags.each do |tag| %>
			<span class="single-tag-box"><%= tag.name %></span>
		<% end %>
	</ul>
<% end %>