config/routes.rb
Rails.application.routes.draw do

    devise_for :users

    #messages
    resources :conversations do
      resources :messages
    end

    #users
    get 'users/:id' => 'users#show'
    resources :users, only: [:show] do
      resources :reviews
    end

    #posts & resource tags
    resources :posts

    resources :transactions


    #tags
    resources :tags, only: [:create]

    #post tags
    resources :post_tags, only: [:create, :destroy]

    #categories
    resources :categories, only: [:index, :show] do
      resources :posts, only: [:index, :show]
    end

    #Sessions routes
    resources :sessions, only: [:create, :new]
    delete 'sessions', to: 'sessions#logout'

    # resources :search, only: [:index]
    get '/search', :to => 'search#index'

  root to: 'categories#index'
end

app/views/layouts/_errors.html.erb
 <% if @errors %>
    <div id="error_explanation">
      <ul>
        <% @errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foreveraloaner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag   'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="row">
      <div class="left-body-column">
        <ul class="nav">
          <li class="nav-li"><%= link_to "Home", categories_path  %></li>
            <% if user_signed_in?  %>
                <li class="nav-li"><%= link_to "Logout", destroy_user_session_path, method: "DELETE" %></li>
                <li class="nav-li"> <%= link_to "My Profile", user_path(current_user)  %></li>
                <li class="nav-li"><%= link_to "Create a Post", new_post_path  %></li>
                <li class="nav-li"><%= link_to "Chats", conversations_path %></li>
            <% else %>
                <li class="nav-li"><%= link_to "Login", new_user_session_path %></li>
                <li class="nav-li"><%= link_to "Register", new_user_registration_path  %></li>
            <% end %>
          </ul>

        <div class="search-bar">
          <%= form_tag(posts_path, method: :get, :class => 'search-style') do %>
            <%= text_field_tag :term, params[:term], placeholder: "Keyword", class: 'col-md-5 input-lg keyword-box' %>
            <%= text_field_tag :zip_code, params[:zip_code], placeholder: "Zip Code", class:"col-md-3 input-lg" %>
            <%= text_field_tag :distance, params[:distance], placeholder: "Miles", class:"col-md-3 input-lg" %>
            <%= submit_tag 'Search', name: nil, class: 'col-md-12 btn'  %>
          <% end %>
        </div>

        <div class="dropdown">
          <button class="dropbtn">Categories</button>
            <div class='dropdown-content'>
              <ul class='menu-scroll'>
                <% @categories.each do |category| %>
                  <%= link_to category.name, category_path(category) %>
                <% end %>
             </ul>
           </div>
         </div>
        </div>
    </div>

    <div class="right-body-column"%>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>



        <%= render "layouts/errors" %>



      <div class="body"><%= yield %></div>
    </div>
  </body>
</html>